# Generated by Django 4.1 on 2023-01-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.TextField(blank=True)),
                ("phone", models.IntegerField()),
                ("message", models.TextField(blank=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
